### ISSUE TITLE
TARDIS waypoint travel will travel to the saved coordinates but not the target dimension the coordinates were saved in

### ISSUE THREAD

**Issue by Yuna-04** [CommandrMoose/TardisRefined#366]
### Issue description

The TARDIS will travel to a saved waypoint's coordinates, but not the dimension the coordinates are saved in. So for example if you save a waypoint in The Nether and return to the Overworld but move the TARDIS, next time you try and travel to that saved waypoint the ship travels to only the coordinates, not the dimension as well. This is strange as it doesn't happen if you save a waypoint in the Overworld and travel to a saved waypoint from another dimension/the Overworld. (This also happens whether or not you use the landing pad, I should add).

Tested with no other mods installed.

Attached video: https://youtu.be/6GzHERo-X5A

### Steps to reproduce

1. Save a waypoint in another dimension thats not the Overworld
2. Return to the Overworld and move the TARDIS to another set of coords in the Overworld
3. Travel to the waypoint that was set in the other dimension
4. When you land you should only be at the waypoint's coordinates in the Overworld, not the dimension as well

### Minecraft version

1.20.1

### Mod Loader Platform type

Forge

### Mod Loader version

Forge 47.2.30

### Tardis Refined version

v2.0.7

**Comment by Yuna-04** [comment]
- I have also tested this on the latest Forge version and the bug still occurs.

**Comment by Jeryn99** [comment]
Stale bot no

**Comment by Jeryn99** [comment]
Should be fixed

**Comment by GoldeRuby** [comment]
playing mod ver 2.1.6
still having this issue
i did a double-take when the dimension was incorrect on the gps but managed to put in the right dimension before travelling
unsure what exactly could be causing it, the only additional dimensions come from FSang18's Heropack
